package org.trustel.privilege;
import java.util.Date;

/**
 * ProductPackOrderRecord generated by MyEclipse Persistence Tools
 */
public class ProductPackOrderRecord	implements java.io.Serializable {

	/**
	 * @Fields serialVersionUID: TODO
	 */
	private static final long serialVersionUID = 1L;

	private String id;
	/**
	 * 商家id
	 */
	private String merchantId;
	/**
	 * 商家名称
	 */
	private String merchantName;
	/**
	 * 产品包id
	 */
	private String packageId;
	/**
	 * 产品包名称
	 */
	private String packageName;
	/**
	 * 产品包角色
	 */
	private String roleCode;
	/**
	 * 生效时间
	 */
	private Date startTime;
	/**
	 * 失效时间
	 */
	private Date endTime;
	/**
	 * 购买期限
	 */
	private Integer buyingTime;
	/**
	 * 更新时间
	 */
	private Date updateTime;
	/**
	 * 状态
	 */
	private Integer status;

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getMerchantId() {
		return this.merchantId;
	}

	public void setMerchantId(String merchantId) {
		this.merchantId = merchantId;
	}

	public String getMerchantName() {
		return this.merchantName;
	}

	public void setMerchantName(String merchantName) {
		this.merchantName = merchantName;
	}

	public String getPackageId() {
		return this.packageId;
	}

	public void setPackageId(String packageId) {
		this.packageId = packageId;
	}

	public String getRoleCode() {
		return this.roleCode;
	}

	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Integer getBuyingTime() {
		return this.buyingTime;
	}

	public void setBuyingTime(Integer buyingTime) {
		this.buyingTime = buyingTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Date getEndTime() {
		return endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public String getPackageName() {
		return packageName;
	}

	public void setPackageName(String packageName) {
		this.packageName = packageName;
	}
}
